version: "3.7"
services:
  kdc:
    build: kdc
    image: gaborgsomogyi/kdc:latest
    env_file: kerberos.env
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - /dev/urandom:/dev/random

  client:
    build: kdc-client
    image: gaborgsomogyi/kdc-client:latest
    env_file: kerberos.env
    depends_on:
      - kdc

# NOTE:
#  "env_file: kerberos.env" is optional.
#  In case no .env file is supplied, nor any environment variable is set, the following values will be used:
#   REALM=EXAMPLE.COM
#   SUPPORTED_ENCRYPTION_TYPES=aes256-cts-hmac-sha1-96:normal
#   KADMIN_PRINCIPAL=kadmin/admin
#   KADMIN_PASSWORD=kadmin
