apiVersion: v1
kind: Service
metadata:
  name: kdc
spec:
  selector:
    name: kdc
  clusterIP: None
  ports:
  - name: kdc
    port: 88
    targetPort: 88
  - name: admin
    port: 749
    targetPort: 749
---

apiVersion: v1
kind: Pod
metadata:
  name: kdc
  labels:
    name: kdc
spec:
  containers:
    - image: gaborgsomogyi/kdc:latest
      imagePullPolicy: Never
      name: kdc
      volumeMounts:
        - mountPath: /share
          name: volume
  volumes:
    - name: volume
      hostPath:
        path: /share
        type: Directory
